import { Space_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar";
import SubscribeForm from "@/components/SubscribeForm";
import Footer from "@/components/Footer";
import { CartContextProvider } from "@/context/CartContext";

const spaceMono = Space_Mono({
  weight: ['400', '700'],
  subsets: ['latin'],
});

export const metadata = {
  title: "CHRISSTORE",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={spaceMono.className}>
        <CartContextProvider>
          <Navbar />
          {children}
          <SubscribeForm />
          <Footer />
        </CartContextProvider>
      </body>
    </html>
  );
}
